In [1]:
import pandas as pd
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float, 'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str, 'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':float, 'condition':int, 'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

sales = pd.read_csv('kc_house_data.csv', dtype=dtype_dict)
sales = sales.sort(['sqft_living','price'])

/Users/junjieyang/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:5: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)


In [2]:
l2_small_penalty = 1.5e-5

In [3]:
def polynomial_dataframe(feature, degree): # feature is pandas.Series type
    # assume that degree >= 1
    # initialize the dataframe:
    poly_dataframe = pd.DataFrame()
    # and set poly_dataframe['power_1'] equal to the passed feature
    poly_dataframe['power_1']=feature
    # first check if degree > 1
    if degree > 1:
        # then loop over the remaining degrees:
        for power in range(2, degree+1):
            # first we'll give the column a name:
            name = 'power_' + str(power)
            # assign poly_dataframe[name] to be feature^power; use apply(*)
            poly_dataframe[name]=feature.apply(lambda x : x**power)
    return poly_dataframe

In [4]:
from sklearn import linear_model
import numpy as np

poly15_data = polynomial_dataframe(sales['sqft_living'], 15) # use equivalent of `polynomial_sframe`
model = linear_model.Ridge(alpha=l2_small_penalty, normalize=True)
model.fit(poly15_data, sales['price'])

Ridge(alpha=1.5e-05, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=True, solver='auto', tol=0.001)

In [5]:
model.coef_

array([  1.24873306e+02,  -4.77376011e-02,   3.01446238e-05,
        -2.44419942e-09,  -1.94153675e-13,   8.54085686e-18,
         1.51142121e-21,   8.27979094e-26,   6.52603100e-31,
        -3.27895017e-34,  -3.87962315e-38,  -2.72437650e-42,
        -1.07790800e-46,   3.78242694e-51,   1.39790296e-54])

In [6]:
set_1 = pd.read_csv('wk3_kc_house_set_1_data.csv', dtype=dtype_dict)
set_2 = pd.read_csv('wk3_kc_house_set_2_data.csv', dtype=dtype_dict)
set_3 = pd.read_csv('wk3_kc_house_set_3_data.csv', dtype=dtype_dict)
set_4 = pd.read_csv('wk3_kc_house_set_4_data.csv', dtype=dtype_dict)
l2_small_penalty=1e-9

In [7]:
mode11=linear_model.Ridge(alpha=l2_small_penalty,normalize=True)
model2=linear_model.Ridge(alpha=l2_small_penalty,normalize=True)
model3=linear_model.Ridge(alpha=l2_small_penalty,normalize=True)
model4=linear_model.Ridge(alpha=l2_small_penalty,normalize=True)

In [8]:
co=[]
for i in [set_1,set_2,set_3,set_4]:
    poly15_data=polynomial_dataframe(i['sqft_living'], 15)
    mode11.fit(poly15_data,i['price'])
    co.append(mode11.coef_)

In [9]:
co

[array([  5.44669404e+02,  -3.55447612e-01,   1.22446386e-04,
         -1.17175331e-08,  -3.90512151e-13,  -1.39076510e-17,
          1.47860281e-20,   6.87492303e-25,  -7.57204442e-29,
         -1.04097282e-32,  -3.71844139e-37,   3.39989255e-41,
          5.56592001e-45,   2.53761440e-49,  -3.35152933e-53]),
 array([  8.59362634e+02,  -8.18118229e-01,   4.28879925e-04,
         -9.12770316e-08,  -2.69605490e-12,   3.73980477e-15,
         -1.42712001e-19,  -6.30794699e-23,  -1.44559628e-27,
          7.44321314e-31,   9.25865930e-35,   3.28031038e-41,
         -1.29543524e-42,  -1.38781275e-46,   1.66546461e-50]),
 array([ -7.55395878e+02,   9.75579426e-01,  -4.58945927e-04,
          7.77957805e-08,   7.15014049e-12,  -2.88602048e-15,
         -2.13678386e-20,   3.38085342e-23,   2.19178191e-27,
         -1.97067920e-31,  -4.15993104e-35,  -1.80196115e-39,
          3.19071133e-43,   5.08456894e-47,  -3.93304251e-51]),
 array([  1.11944588e+03,  -9.83760498e-01,   3.38771137e-04,
  

In [10]:
l2_large_penalty=1.23e2
modelnew=linear_model.Ridge(alpha=l2_large_penalty,normalize=True)

In [11]:
co=[]
for i in [set_1,set_2,set_3,set_4]:
    poly15_data=polynomial_dataframe(i['sqft_living'], 15)
    modelnew.fit(poly15_data,i['price'])
    co.append(modelnew.coef_)
co

[array([  2.32806803e+00,   3.53621608e-04,   3.31969692e-08,
          2.00082477e-12,   1.11492559e-16,   6.57786122e-21,
          4.12939525e-25,   2.70393755e-29,   1.81614763e-33,
          1.23824277e-37,   8.51872481e-42,   5.89455598e-46,
          4.09542560e-50,   2.85464889e-54,   1.99547476e-58]),
 array([  2.09756903e+00,   3.90817483e-04,   6.67189944e-08,
          8.90002997e-12,   9.72639877e-16,   9.69733682e-20,
          9.50564475e-24,   9.44491031e-28,   9.57191338e-32,
          9.86945155e-36,   1.03101115e-39,   1.08729784e-43,
          1.15453748e-47,   1.23211305e-51,   1.31986696e-55]),
 array([  2.28906258e+00,   4.12472190e-04,   6.08835345e-08,
          6.58572163e-12,   6.15278155e-16,   5.64446634e-20,
          5.28834396e-24,   5.07091402e-28,   4.94657273e-32,
          4.88043809e-36,   4.85009106e-40,   4.84161534e-44,
          4.84635021e-48,   4.85883628e-52,   4.87558469e-56]),
 array([  2.08596194e+00,   4.05035772e-04,   7.46864647e-08,
  

## K-fold

In [12]:
train_valid_shuffled = pd.read_csv('wk3_kc_house_train_valid_shuffled.csv', dtype=dtype_dict)
test = pd.read_csv('wk3_kc_house_test_data.csv', dtype=dtype_dict)

In [13]:
n = len(train_valid_shuffled)
k = 10 # 10-fold cross-validation
print n
for i in xrange(k):
    start = (n*i)/k
    end = (n*(i+1))/k-1
    print i, (start, end)

19396
0 (0, 1938)
1 (1939, 3878)
2 (3879, 5817)
3 (5818, 7757)
4 (7758, 9697)
5 (9698, 11636)
6 (11637, 13576)
7 (13577, 15515)
8 (15516, 17455)
9 (17456, 19395)


In [ ]:
trainset=[]
for i in range(0,10):
    start=(n*i)/10
    end=(n*(i+1))/10
    trainset.append(train_valid_shuffled[start:end])

In [14]:
def kfold(k,l2_penalty,data):
    trainset=[]
    valiset=[]
    n=len(data)
    for i in range(0,k):
        start=(n*i)/k
        end=(n*(i+1))/k
        valiset.append(train_valid_shuffled[start:end+1])
        train=train_valid_shuffled[0:start].append(train_valid_shuffled[end+1:n])
        trainset.append(train)
    allrss=0.0
    for i in range(0,k):
        poly15_data=polynomial_dataframe(trainset[i]['sqft_living'], 15)
        poly15_data2=polynomial_dataframe(valiset[i]['sqft_living'],15)
        model=linear_model.Ridge(alpha=l2_penalty,normalize=True)
        model.fit(poly15_data,trainset[i]['price'])
        rss=np.sum((valiset[i]['price']-model.predict(poly15_data2))**2)
        allrss=allrss+rss
    return allrss/k        

In [26]:
for i in [10.0**3,10**3.5,10**4,10**4.5,10**5,10**5.5,10**6.0,10**6.5,10**7,10**7.5,10**8,10**8.5,10**9]:
    print i,kfold(10,i,train_valid_shuffled)

1000.0 2.65017874562e+14
3162.27766017 2.6573349394e+14
10000 2.65964941178e+14
31622.7766017 2.66038658207e+14
100000 2.66062022668e+14
316227.766017 2.6606941648e+14
1000000.0 2.66071755142e+14
3162277.66017 2.66072494744e+14
10000000 2.66072728633e+14
31622776.6017 2.66072802595e+14
100000000 2.66072825984e+14
316227766.017 2.66072833381e+14
1000000000 2.6607283572e+14


In [16]:
ls

Overfitting_Demo_Ridge_Lasso.ipynb     wk3_kc_house_set_3_data.csv
Untitled.ipynb                         wk3_kc_house_set_4_data.csv
kc_house_data.csv*                     wk3_kc_house_test_data.csv*
week4_ridgeregression-annotated.pdf    wk3_kc_house_train_data.csv*
wk3_kc_house_set_1_data.csv            wk3_kc_house_train_valid_shuffled.csv
wk3_kc_house_set_2_data.csv            wk3_kc_house_valid_data.csv*


In [17]:
alltrain=pd.read_csv('wk3_kc_house_train_data.csv', dtype=dtype_dict)
alltest=pd.read_csv('wk3_kc_house_test_data.csv', dtype=dtype_dict)

In [24]:
l2_penalty=3162.27766017
poly15_data=polynomial_dataframe(alltrain['sqft_living'], 15)
poly15_data2=polynomial_dataframe(alltest['sqft_living'],15)
model=linear_model.Ridge(alpha=l2_penalty,normalize=True)
model.fit(poly15_data,alltrain['price'])
rss=np.sum((alltest['price']-model.predict(poly15_data2))**2)

In [25]:
rss

284413196489360.4